// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_id", Type: field.TypeString, Unique: true},
		{Name: "run_id", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "TIMESTAMPTZ", "sqlite3": "DATETIME"}},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_run_id_seq",
				Unique:  true,
				Columns: []*schema.Column{EventsColumns[2], EventsColumns[3]},
			},
			{
				Name:    "event_run_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2]},
			},
		},
	}
	// SnapshotsColumns holds the columns for the "snapshots" table.
	SnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "snapshot_id", Type: field.TypeString, Unique: true},
		{Name: "run_id", Type: field.TypeString},
		{Name: "upto_seq", Type: field.TypeInt64},
		{Name: "state", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "TIMESTAMPTZ", "sqlite3": "DATETIME"}},
	}
	// SnapshotsTable holds the schema information for the "snapshots" table.
	SnapshotsTable = &schema.Table{
		Name:       "snapshots",
		Columns:    SnapshotsColumns,
		PrimaryKey: []*schema.Column{SnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snapshot_run_id",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[2]},
			},
			{
				Name:    "snapshot_run_id_upto_seq",
				Unique:  true,
				Columns: []*schema.Column{SnapshotsColumns[2], SnapshotsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		SnapshotsTable,
	}
)

func init() {
}
