// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wilhg/orch/internal/ent/event"
	"github.com/wilhg/orch/internal/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetEventID sets the "event_id" field.
func (eu *EventUpdate) SetEventID(s string) *EventUpdate {
	eu.mutation.SetEventID(s)
	return eu
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (eu *EventUpdate) SetNillableEventID(s *string) *EventUpdate {
	if s != nil {
		eu.SetEventID(*s)
	}
	return eu
}

// SetRunID sets the "run_id" field.
func (eu *EventUpdate) SetRunID(s string) *EventUpdate {
	eu.mutation.SetRunID(s)
	return eu
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (eu *EventUpdate) SetNillableRunID(s *string) *EventUpdate {
	if s != nil {
		eu.SetRunID(*s)
	}
	return eu
}

// SetSeq sets the "seq" field.
func (eu *EventUpdate) SetSeq(i int64) *EventUpdate {
	eu.mutation.ResetSeq()
	eu.mutation.SetSeq(i)
	return eu
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (eu *EventUpdate) SetNillableSeq(i *int64) *EventUpdate {
	if i != nil {
		eu.SetSeq(*i)
	}
	return eu
}

// AddSeq adds i to the "seq" field.
func (eu *EventUpdate) AddSeq(i int64) *EventUpdate {
	eu.mutation.AddSeq(i)
	return eu
}

// SetType sets the "type" field.
func (eu *EventUpdate) SetType(s string) *EventUpdate {
	eu.mutation.SetType(s)
	return eu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (eu *EventUpdate) SetNillableType(s *string) *EventUpdate {
	if s != nil {
		eu.SetType(*s)
	}
	return eu
}

// SetPayload sets the "payload" field.
func (eu *EventUpdate) SetPayload(m map[string]interface{}) *EventUpdate {
	eu.mutation.SetPayload(m)
	return eu
}

// ClearPayload clears the value of the "payload" field.
func (eu *EventUpdate) ClearPayload() *EventUpdate {
	eu.mutation.ClearPayload()
	return eu
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.EventID(); ok {
		if err := event.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "Event.event_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.RunID(); ok {
		if err := event.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Event.run_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Seq(); ok {
		if err := event.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "Event.seq": %w`, err)}
		}
	}
	if v, ok := eu.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeString, value)
	}
	if value, ok := eu.mutation.RunID(); ok {
		_spec.SetField(event.FieldRunID, field.TypeString, value)
	}
	if value, ok := eu.mutation.Seq(); ok {
		_spec.SetField(event.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := eu.mutation.AddedSeq(); ok {
		_spec.AddField(event.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := eu.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := eu.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if eu.mutation.PayloadCleared() {
		_spec.ClearField(event.FieldPayload, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetEventID sets the "event_id" field.
func (euo *EventUpdateOne) SetEventID(s string) *EventUpdateOne {
	euo.mutation.SetEventID(s)
	return euo
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEventID(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetEventID(*s)
	}
	return euo
}

// SetRunID sets the "run_id" field.
func (euo *EventUpdateOne) SetRunID(s string) *EventUpdateOne {
	euo.mutation.SetRunID(s)
	return euo
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableRunID(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetRunID(*s)
	}
	return euo
}

// SetSeq sets the "seq" field.
func (euo *EventUpdateOne) SetSeq(i int64) *EventUpdateOne {
	euo.mutation.ResetSeq()
	euo.mutation.SetSeq(i)
	return euo
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableSeq(i *int64) *EventUpdateOne {
	if i != nil {
		euo.SetSeq(*i)
	}
	return euo
}

// AddSeq adds i to the "seq" field.
func (euo *EventUpdateOne) AddSeq(i int64) *EventUpdateOne {
	euo.mutation.AddSeq(i)
	return euo
}

// SetType sets the "type" field.
func (euo *EventUpdateOne) SetType(s string) *EventUpdateOne {
	euo.mutation.SetType(s)
	return euo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableType(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetType(*s)
	}
	return euo
}

// SetPayload sets the "payload" field.
func (euo *EventUpdateOne) SetPayload(m map[string]interface{}) *EventUpdateOne {
	euo.mutation.SetPayload(m)
	return euo
}

// ClearPayload clears the value of the "payload" field.
func (euo *EventUpdateOne) ClearPayload() *EventUpdateOne {
	euo.mutation.ClearPayload()
	return euo
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// Where appends a list predicates to the EventUpdate builder.
func (euo *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.EventID(); ok {
		if err := event.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "Event.event_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.RunID(); ok {
		if err := event.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Event.run_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Seq(); ok {
		if err := event.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "Event.seq": %w`, err)}
		}
	}
	if v, ok := euo.mutation.GetType(); ok {
		if err := event.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Event.type": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.EventID(); ok {
		_spec.SetField(event.FieldEventID, field.TypeString, value)
	}
	if value, ok := euo.mutation.RunID(); ok {
		_spec.SetField(event.FieldRunID, field.TypeString, value)
	}
	if value, ok := euo.mutation.Seq(); ok {
		_spec.SetField(event.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := euo.mutation.AddedSeq(); ok {
		_spec.AddField(event.FieldSeq, field.TypeInt64, value)
	}
	if value, ok := euo.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
	}
	if value, ok := euo.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if euo.mutation.PayloadCleared() {
		_spec.ClearField(event.FieldPayload, field.TypeJSON)
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
