// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/wilhg/orch/internal/ent/event"
	"github.com/wilhg/orch/internal/ent/schema"
	"github.com/wilhg/orch/internal/ent/snapshot"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescEventID is the schema descriptor for event_id field.
	eventDescEventID := eventFields[0].Descriptor()
	// event.EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	event.EventIDValidator = eventDescEventID.Validators[0].(func(string) error)
	// eventDescRunID is the schema descriptor for run_id field.
	eventDescRunID := eventFields[1].Descriptor()
	// event.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	event.RunIDValidator = eventDescRunID.Validators[0].(func(string) error)
	// eventDescSeq is the schema descriptor for seq field.
	eventDescSeq := eventFields[2].Descriptor()
	// event.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	event.SeqValidator = eventDescSeq.Validators[0].(func(int64) error)
	// eventDescType is the schema descriptor for type field.
	eventDescType := eventFields[3].Descriptor()
	// event.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	event.TypeValidator = eventDescType.Validators[0].(func(string) error)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[5].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	snapshotFields := schema.Snapshot{}.Fields()
	_ = snapshotFields
	// snapshotDescSnapshotID is the schema descriptor for snapshot_id field.
	snapshotDescSnapshotID := snapshotFields[0].Descriptor()
	// snapshot.SnapshotIDValidator is a validator for the "snapshot_id" field. It is called by the builders before save.
	snapshot.SnapshotIDValidator = snapshotDescSnapshotID.Validators[0].(func(string) error)
	// snapshotDescRunID is the schema descriptor for run_id field.
	snapshotDescRunID := snapshotFields[1].Descriptor()
	// snapshot.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	snapshot.RunIDValidator = snapshotDescRunID.Validators[0].(func(string) error)
	// snapshotDescUptoSeq is the schema descriptor for upto_seq field.
	snapshotDescUptoSeq := snapshotFields[2].Descriptor()
	// snapshot.UptoSeqValidator is a validator for the "upto_seq" field. It is called by the builders before save.
	snapshot.UptoSeqValidator = snapshotDescUptoSeq.Validators[0].(func(int64) error)
	// snapshotDescCreatedAt is the schema descriptor for created_at field.
	snapshotDescCreatedAt := snapshotFields[4].Descriptor()
	// snapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	snapshot.DefaultCreatedAt = snapshotDescCreatedAt.Default.(func() time.Time)
}
