// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wilhg/orch/internal/ent/snapshot"
)

// SnapshotCreate is the builder for creating a Snapshot entity.
type SnapshotCreate struct {
	config
	mutation *SnapshotMutation
	hooks    []Hook
}

// SetSnapshotID sets the "snapshot_id" field.
func (sc *SnapshotCreate) SetSnapshotID(s string) *SnapshotCreate {
	sc.mutation.SetSnapshotID(s)
	return sc
}

// SetRunID sets the "run_id" field.
func (sc *SnapshotCreate) SetRunID(s string) *SnapshotCreate {
	sc.mutation.SetRunID(s)
	return sc
}

// SetUptoSeq sets the "upto_seq" field.
func (sc *SnapshotCreate) SetUptoSeq(i int64) *SnapshotCreate {
	sc.mutation.SetUptoSeq(i)
	return sc
}

// SetState sets the "state" field.
func (sc *SnapshotCreate) SetState(m map[string]interface{}) *SnapshotCreate {
	sc.mutation.SetState(m)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SnapshotCreate) SetCreatedAt(t time.Time) *SnapshotCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SnapshotCreate) SetNillableCreatedAt(t *time.Time) *SnapshotCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// Mutation returns the SnapshotMutation object of the builder.
func (sc *SnapshotCreate) Mutation() *SnapshotMutation {
	return sc.mutation
}

// Save creates the Snapshot in the database.
func (sc *SnapshotCreate) Save(ctx context.Context) (*Snapshot, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SnapshotCreate) SaveX(ctx context.Context) *Snapshot {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SnapshotCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SnapshotCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SnapshotCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := snapshot.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SnapshotCreate) check() error {
	if _, ok := sc.mutation.SnapshotID(); !ok {
		return &ValidationError{Name: "snapshot_id", err: errors.New(`ent: missing required field "Snapshot.snapshot_id"`)}
	}
	if v, ok := sc.mutation.SnapshotID(); ok {
		if err := snapshot.SnapshotIDValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.snapshot_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "Snapshot.run_id"`)}
	}
	if v, ok := sc.mutation.RunID(); ok {
		if err := snapshot.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.run_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.UptoSeq(); !ok {
		return &ValidationError{Name: "upto_seq", err: errors.New(`ent: missing required field "Snapshot.upto_seq"`)}
	}
	if v, ok := sc.mutation.UptoSeq(); ok {
		if err := snapshot.UptoSeqValidator(v); err != nil {
			return &ValidationError{Name: "upto_seq", err: fmt.Errorf(`ent: validator failed for field "Snapshot.upto_seq": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Snapshot.created_at"`)}
	}
	return nil
}

func (sc *SnapshotCreate) sqlSave(ctx context.Context) (*Snapshot, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SnapshotCreate) createSpec() (*Snapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &Snapshot{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(snapshot.Table, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.SnapshotID(); ok {
		_spec.SetField(snapshot.FieldSnapshotID, field.TypeString, value)
		_node.SnapshotID = value
	}
	if value, ok := sc.mutation.RunID(); ok {
		_spec.SetField(snapshot.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := sc.mutation.UptoSeq(); ok {
		_spec.SetField(snapshot.FieldUptoSeq, field.TypeInt64, value)
		_node.UptoSeq = value
	}
	if value, ok := sc.mutation.State(); ok {
		_spec.SetField(snapshot.FieldState, field.TypeJSON, value)
		_node.State = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(snapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SnapshotCreateBulk is the builder for creating many Snapshot entities in bulk.
type SnapshotCreateBulk struct {
	config
	err      error
	builders []*SnapshotCreate
}

// Save creates the Snapshot entities in the database.
func (scb *SnapshotCreateBulk) Save(ctx context.Context) ([]*Snapshot, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Snapshot, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SnapshotCreateBulk) SaveX(ctx context.Context) []*Snapshot {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
