// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wilhg/orch/internal/ent/predicate"
	"github.com/wilhg/orch/internal/ent/snapshot"
)

// SnapshotUpdate is the builder for updating Snapshot entities.
type SnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SnapshotMutation
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (su *SnapshotUpdate) Where(ps ...predicate.Snapshot) *SnapshotUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSnapshotID sets the "snapshot_id" field.
func (su *SnapshotUpdate) SetSnapshotID(s string) *SnapshotUpdate {
	su.mutation.SetSnapshotID(s)
	return su
}

// SetNillableSnapshotID sets the "snapshot_id" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableSnapshotID(s *string) *SnapshotUpdate {
	if s != nil {
		su.SetSnapshotID(*s)
	}
	return su
}

// SetRunID sets the "run_id" field.
func (su *SnapshotUpdate) SetRunID(s string) *SnapshotUpdate {
	su.mutation.SetRunID(s)
	return su
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableRunID(s *string) *SnapshotUpdate {
	if s != nil {
		su.SetRunID(*s)
	}
	return su
}

// SetUptoSeq sets the "upto_seq" field.
func (su *SnapshotUpdate) SetUptoSeq(i int64) *SnapshotUpdate {
	su.mutation.ResetUptoSeq()
	su.mutation.SetUptoSeq(i)
	return su
}

// SetNillableUptoSeq sets the "upto_seq" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableUptoSeq(i *int64) *SnapshotUpdate {
	if i != nil {
		su.SetUptoSeq(*i)
	}
	return su
}

// AddUptoSeq adds i to the "upto_seq" field.
func (su *SnapshotUpdate) AddUptoSeq(i int64) *SnapshotUpdate {
	su.mutation.AddUptoSeq(i)
	return su
}

// SetState sets the "state" field.
func (su *SnapshotUpdate) SetState(m map[string]interface{}) *SnapshotUpdate {
	su.mutation.SetState(m)
	return su
}

// ClearState clears the value of the "state" field.
func (su *SnapshotUpdate) ClearState() *SnapshotUpdate {
	su.mutation.ClearState()
	return su
}

// Mutation returns the SnapshotMutation object of the builder.
func (su *SnapshotUpdate) Mutation() *SnapshotMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SnapshotUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SnapshotUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SnapshotUpdate) check() error {
	if v, ok := su.mutation.SnapshotID(); ok {
		if err := snapshot.SnapshotIDValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.snapshot_id": %w`, err)}
		}
	}
	if v, ok := su.mutation.RunID(); ok {
		if err := snapshot.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.run_id": %w`, err)}
		}
	}
	if v, ok := su.mutation.UptoSeq(); ok {
		if err := snapshot.UptoSeqValidator(v); err != nil {
			return &ValidationError{Name: "upto_seq", err: fmt.Errorf(`ent: validator failed for field "Snapshot.upto_seq": %w`, err)}
		}
	}
	return nil
}

func (su *SnapshotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.SnapshotID(); ok {
		_spec.SetField(snapshot.FieldSnapshotID, field.TypeString, value)
	}
	if value, ok := su.mutation.RunID(); ok {
		_spec.SetField(snapshot.FieldRunID, field.TypeString, value)
	}
	if value, ok := su.mutation.UptoSeq(); ok {
		_spec.SetField(snapshot.FieldUptoSeq, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedUptoSeq(); ok {
		_spec.AddField(snapshot.FieldUptoSeq, field.TypeInt64, value)
	}
	if value, ok := su.mutation.State(); ok {
		_spec.SetField(snapshot.FieldState, field.TypeJSON, value)
	}
	if su.mutation.StateCleared() {
		_spec.ClearField(snapshot.FieldState, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SnapshotUpdateOne is the builder for updating a single Snapshot entity.
type SnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SnapshotMutation
}

// SetSnapshotID sets the "snapshot_id" field.
func (suo *SnapshotUpdateOne) SetSnapshotID(s string) *SnapshotUpdateOne {
	suo.mutation.SetSnapshotID(s)
	return suo
}

// SetNillableSnapshotID sets the "snapshot_id" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableSnapshotID(s *string) *SnapshotUpdateOne {
	if s != nil {
		suo.SetSnapshotID(*s)
	}
	return suo
}

// SetRunID sets the "run_id" field.
func (suo *SnapshotUpdateOne) SetRunID(s string) *SnapshotUpdateOne {
	suo.mutation.SetRunID(s)
	return suo
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableRunID(s *string) *SnapshotUpdateOne {
	if s != nil {
		suo.SetRunID(*s)
	}
	return suo
}

// SetUptoSeq sets the "upto_seq" field.
func (suo *SnapshotUpdateOne) SetUptoSeq(i int64) *SnapshotUpdateOne {
	suo.mutation.ResetUptoSeq()
	suo.mutation.SetUptoSeq(i)
	return suo
}

// SetNillableUptoSeq sets the "upto_seq" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableUptoSeq(i *int64) *SnapshotUpdateOne {
	if i != nil {
		suo.SetUptoSeq(*i)
	}
	return suo
}

// AddUptoSeq adds i to the "upto_seq" field.
func (suo *SnapshotUpdateOne) AddUptoSeq(i int64) *SnapshotUpdateOne {
	suo.mutation.AddUptoSeq(i)
	return suo
}

// SetState sets the "state" field.
func (suo *SnapshotUpdateOne) SetState(m map[string]interface{}) *SnapshotUpdateOne {
	suo.mutation.SetState(m)
	return suo
}

// ClearState clears the value of the "state" field.
func (suo *SnapshotUpdateOne) ClearState() *SnapshotUpdateOne {
	suo.mutation.ClearState()
	return suo
}

// Mutation returns the SnapshotMutation object of the builder.
func (suo *SnapshotUpdateOne) Mutation() *SnapshotMutation {
	return suo.mutation
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (suo *SnapshotUpdateOne) Where(ps ...predicate.Snapshot) *SnapshotUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SnapshotUpdateOne) Select(field string, fields ...string) *SnapshotUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Snapshot entity.
func (suo *SnapshotUpdateOne) Save(ctx context.Context) (*Snapshot, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SnapshotUpdateOne) SaveX(ctx context.Context) *Snapshot {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SnapshotUpdateOne) check() error {
	if v, ok := suo.mutation.SnapshotID(); ok {
		if err := snapshot.SnapshotIDValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.snapshot_id": %w`, err)}
		}
	}
	if v, ok := suo.mutation.RunID(); ok {
		if err := snapshot.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Snapshot.run_id": %w`, err)}
		}
	}
	if v, ok := suo.mutation.UptoSeq(); ok {
		if err := snapshot.UptoSeqValidator(v); err != nil {
			return &ValidationError{Name: "upto_seq", err: fmt.Errorf(`ent: validator failed for field "Snapshot.upto_seq": %w`, err)}
		}
	}
	return nil
}

func (suo *SnapshotUpdateOne) sqlSave(ctx context.Context) (_node *Snapshot, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Snapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snapshot.FieldID)
		for _, f := range fields {
			if !snapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.SnapshotID(); ok {
		_spec.SetField(snapshot.FieldSnapshotID, field.TypeString, value)
	}
	if value, ok := suo.mutation.RunID(); ok {
		_spec.SetField(snapshot.FieldRunID, field.TypeString, value)
	}
	if value, ok := suo.mutation.UptoSeq(); ok {
		_spec.SetField(snapshot.FieldUptoSeq, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedUptoSeq(); ok {
		_spec.AddField(snapshot.FieldUptoSeq, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.State(); ok {
		_spec.SetField(snapshot.FieldState, field.TypeJSON, value)
	}
	if suo.mutation.StateCleared() {
		_spec.ClearField(snapshot.FieldState, field.TypeJSON)
	}
	_node = &Snapshot{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
