// Code generated by ent, DO NOT EDIT.

package snapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/wilhg/orch/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldID, id))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldSnapshotID, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldRunID, v))
}

// UptoSeq applies equality check predicate on the "upto_seq" field. It's identical to UptoSeqEQ.
func UptoSeq(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldUptoSeq, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// SnapshotIDGT applies the GT predicate on the "snapshot_id" field.
func SnapshotIDGT(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldSnapshotID, v))
}

// SnapshotIDGTE applies the GTE predicate on the "snapshot_id" field.
func SnapshotIDGTE(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldSnapshotID, v))
}

// SnapshotIDLT applies the LT predicate on the "snapshot_id" field.
func SnapshotIDLT(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldSnapshotID, v))
}

// SnapshotIDLTE applies the LTE predicate on the "snapshot_id" field.
func SnapshotIDLTE(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldSnapshotID, v))
}

// SnapshotIDContains applies the Contains predicate on the "snapshot_id" field.
func SnapshotIDContains(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldContains(FieldSnapshotID, v))
}

// SnapshotIDHasPrefix applies the HasPrefix predicate on the "snapshot_id" field.
func SnapshotIDHasPrefix(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldHasPrefix(FieldSnapshotID, v))
}

// SnapshotIDHasSuffix applies the HasSuffix predicate on the "snapshot_id" field.
func SnapshotIDHasSuffix(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldHasSuffix(FieldSnapshotID, v))
}

// SnapshotIDEqualFold applies the EqualFold predicate on the "snapshot_id" field.
func SnapshotIDEqualFold(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEqualFold(FieldSnapshotID, v))
}

// SnapshotIDContainsFold applies the ContainsFold predicate on the "snapshot_id" field.
func SnapshotIDContainsFold(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldContainsFold(FieldSnapshotID, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldContainsFold(FieldRunID, v))
}

// UptoSeqEQ applies the EQ predicate on the "upto_seq" field.
func UptoSeqEQ(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldUptoSeq, v))
}

// UptoSeqNEQ applies the NEQ predicate on the "upto_seq" field.
func UptoSeqNEQ(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldUptoSeq, v))
}

// UptoSeqIn applies the In predicate on the "upto_seq" field.
func UptoSeqIn(vs ...int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldUptoSeq, vs...))
}

// UptoSeqNotIn applies the NotIn predicate on the "upto_seq" field.
func UptoSeqNotIn(vs ...int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldUptoSeq, vs...))
}

// UptoSeqGT applies the GT predicate on the "upto_seq" field.
func UptoSeqGT(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldUptoSeq, v))
}

// UptoSeqGTE applies the GTE predicate on the "upto_seq" field.
func UptoSeqGTE(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldUptoSeq, v))
}

// UptoSeqLT applies the LT predicate on the "upto_seq" field.
func UptoSeqLT(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldUptoSeq, v))
}

// UptoSeqLTE applies the LTE predicate on the "upto_seq" field.
func UptoSeqLTE(v int64) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldUptoSeq, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotNull(FieldState))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.NotPredicates(p))
}
